name: Production Deployment

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  check:
    uses: ./.github/workflows/quality-checks.yml
    secrets: inherit

  publish-production:
    needs: [check]
    uses: ./.github/workflows/publish-production.yml
    secrets: inherit

  release:
    needs: [netlify-deploy]
    uses: ./.github/workflows/release.yml
    secrets: inherit
