name: Preview Deployment

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  pull-requests: write
  issues: write

jobs:
  check:
    uses: ./.github/workflows/quality-checks.yml
    secrets: inherit

  publish-preview:
    needs: [check]
    uses: ./.github/workflows/publish-preview.yml
    secrets: inherit
